"""
scripts/ingest_pdf.py

Phase 3 CLI smoke test — ingest a PDF and verify it's stored in ChromaDB.

Usage:
    python scripts/ingest_pdf.py path/to/document.pdf
    python scripts/ingest_pdf.py          # uses a generated test PDF

What it does:
  1. Loads config + builds embedding adapter + vector store
  2. Runs the full ingestion pipeline
  3. Verifies the document appears in the registry
  4. Does a test similarity search to confirm vectors are retrievable
  5. Prints a summary and pass/fail
"""

import sys
import os
import time
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from backend.config import get_settings
from backend.adapters.embeddings.factory import EmbeddingAdapterFactory
from backend.services.ingestion import PDFIngestionService
from backend.storage.vector_store import VectorStore


def create_test_pdf(output_path: Path) -> None:
    """Generate a minimal test PDF using PyMuPDF (no external files needed)."""
    import fitz
    doc = fitz.open()
    page = doc.new_page()
    page.insert_text(
        (72, 100),
        (
            "PDF-QA Test Document\n\n"
            "This is a test PDF generated by the ingest_pdf.py script.\n\n"
            "Artificial Intelligence and Machine Learning are transforming industries.\n"
            "Large Language Models (LLMs) like Gemini, GPT-4, and Claude can understand\n"
            "and generate human-like text with remarkable accuracy.\n\n"
            "Retrieval-Augmented Generation (RAG) combines the power of vector search\n"
            "with LLM generation to produce grounded, factual answers from documents.\n\n"
            "ChromaDB is an open-source embedding database that stores text vectors\n"
            "and enables fast similarity search over millions of chunks.\n"
        ),
        fontsize=11,
    )
    doc.save(str(output_path))
    doc.close()


def main() -> None:
    print("\n" + "=" * 60)
    print("  PDF-QA - Ingestion Pipeline Smoke Test")
    print("=" * 60)

    # ── Resolve PDF path ──────────────────────────────────────────────────────
    if len(sys.argv) > 1:
        pdf_path = Path(sys.argv[1])
        if not pdf_path.exists():
            print(f"ERROR: File not found: {pdf_path}")
            sys.exit(1)
        print(f"\nUsing provided PDF: {pdf_path.name}")
    else:
        pdf_path = Path("test_document.pdf")
        print("\nNo PDF provided — generating a test PDF...")
        create_test_pdf(pdf_path)
        print(f"Created: {pdf_path}")

    # ── Build services ────────────────────────────────────────────────────────
    print("\nLoading config and embedding adapter...", end=" ")
    cfg = get_settings()
    embedder = EmbeddingAdapterFactory.create(cfg)
    store = VectorStore(cfg.vector_store, embedder)
    service = PDFIngestionService(store, cfg.chunking)
    print("OK")

    print(f"\nConfig:")
    print(f"  Embedding   : {cfg.embeddings.provider} / {cfg.embeddings.model}")
    print(f"  Chunk size  : {cfg.chunking.chunk_size} chars (overlap {cfg.chunking.chunk_overlap})")
    print(f"  Vector DB   : {cfg.vector_store.persist_directory}")

    # ── PDF stats ─────────────────────────────────────────────────────────────
    stats = service.get_stats(pdf_path)
    print(f"\nPDF stats:")
    print(f"  Pages       : {stats['pages']}")
    print(f"  Characters  : {stats['total_characters']:,}")
    print(f"  Est. chunks : ~{stats['estimated_chunks']}")

    # ── Ingest ────────────────────────────────────────────────────────────────
    print(f"\nIngesting '{pdf_path.name}'...", end=" ", flush=True)
    start = time.perf_counter()
    try:
        doc_record = service.ingest(pdf_path, pdf_path.name)
        elapsed = time.perf_counter() - start
        print(f"OK ({elapsed:.1f}s)")
    except Exception as e:
        print(f"\nERROR: {e}")
        sys.exit(1)

    print(f"\nIngestion result:")
    print(f"  doc_id      : {doc_record.doc_id}")
    print(f"  filename    : {doc_record.filename}")
    print(f"  chunks      : {doc_record.chunk_count}")
    print(f"  size        : {doc_record.file_size_bytes:,} bytes")

    # ── Verify: document appears in registry ──────────────────────────────────
    print("\nVerifying document registry...", end=" ")
    registered = store.get_document(doc_record.doc_id)
    if not registered:
        print("FAIL: doc not found in registry!")
        sys.exit(1)
    print("OK")

    # ── Verify: similarity search works ──────────────────────────────────────
    print("Running test similarity search...", end=" ", flush=True)
    test_query = "What is RAG or retrieval augmented generation?"
    results = store.search(test_query, top_k=3, score_threshold=0.0)
    if not results:
        print("FAIL: no results returned!")
        sys.exit(1)
    print(f"OK ({len(results)} results)")

    print(f"\nTop result (score={results[0].score}):")
    print(f"  Page     : {results[0].metadata.get('page')}")
    print(f"  Text     : {results[0].text[:120]}...")

    # ── Summary ───────────────────────────────────────────────────────────────
    all_docs = store.list_documents()
    print(f"\nTotal documents in vector store: {len(all_docs)}")
    print(f"Total chunks in collection     : {store.chunk_count()}")

    print("\n>> Ingestion pipeline working correctly.\n")


if __name__ == "__main__":
    main()
